name: surrealdb_dart
description: The Flutter SurrealDB package is a powerful integration for Flutter, built upon the foundation of surrealdb, the official SurrealDB library.
version: 1.0.1
homepage: https://github.com/allou-deyforyou/surrealdb.dart
repository: https://github.com/allou-deyforyou/surrealdb.dart

environment:
  sdk: ^3.1.4

dependencies:
  websocket_universal: ^1.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
