// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Int64 Function(ffi.Int64, ffi.Int64)>(symbol: 'add')
external int add(
  int a,
  int b,
);
